const SCRIPTS = [
  {
    id: 'ssh_brute',
    filename: 'ssh_brute.sh',
    description: 'Dictionary-based SSH attack tool. Reliable against unprotected workstations, limited against hardened targets.',
    rarity: 'uncommon',
    category: 'network',
    stats: {},
    cost: 500,
    cpu: 2, ram: 1, gpu: 0,
  },
  {
    id: 'exploit_kit',
    filename: 'exploit_kit.py',
    description: 'Modular exploit framework. Chains known CVEs for access to servers and corporate infrastructure.',
    rarity: 'rare',
    category: 'network',
    stats: {},
    cost: 1800,
    cpu: 4, ram: 4, gpu: 0,
  },
  {
    id: 'corp_bleeder',
    filename: 'corp_bleeder.py',
    description: 'Silent financial drain. Siphons micro-transactions from compromised corporate servers over time. High exposure risk.',
    rarity: 'legendary',
    category: 'network',
    stats: {},
    cost: 5000,
    cpu: 2, ram: 4, gpu: 0,
  },
  {
    id: 'proxy_tunnel',
    filename: 'proxy_tunnel.sh',
    description: 'Routes traffic through anonymous proxy nodes. Core tool for passive bandwidth operations.',
    rarity: 'common',
    category: 'automation',
    stats: {},
    cost: 50,
    cpu: 1, ram: 1, gpu: 0,
    unlocksOperation: 'bandwidth_leasing',
  },
  {
    id: 'scraper_v1',
    filename: 'scraper_v1.py',
    description: 'Harvests and packages user data from public endpoints. Standard automation tool.',
    rarity: 'common',
    category: 'automation',
    stats: {},
    cost: 200,
    cpu: 2, ram: 4, gpu: 0,
    unlocksOperation: 'data_harvesting',
  },
  {
    id: 'hash_cracker',
    filename: 'hash_cracker.py',
    description: 'Brute forces cryptographic hash functions using wordlists and rainbow tables. Cracks wallet hashes (1 at a time) and speeds up contract jobs.',
    rarity: 'uncommon',
    category: 'contract',
    stats: { contractSpeedBonus: 1.3, parallelCracks: 1 },
    cost: 350,
    cpu: 3, ram: 2, gpu: 0,
  },
  {
    id: 'hash_cracker_v2',
    filename: 'hash_cracker_v2.py',
    description: 'Enhanced cracking suite with multi-threaded support. Runs 2 wallet hashes in parallel with improved throughput.',
    rarity: 'rare',
    category: 'contract',
    stats: { contractSpeedBonus: 1.6, parallelCracks: 2 },
    cost: 2200,
    cpu: 5, ram: 4, gpu: 0,
  },
  {
    id: 'hash_cracker_v3',
    filename: 'hash_cracker_v3.py',
    description: 'Military-grade cracking engine. Handles 3 parallel hash jobs with near-optimal throughput and 2× speed.',
    rarity: 'legendary',
    category: 'contract',
    stats: { contractSpeedBonus: 2.0, parallelCracks: 3 },
    cost: 7500,
    cpu: 6, ram: 8, gpu: 2,
  },
  {
    id: 'payload_inj',
    filename: 'payload_inj.sh',
    description: 'Injects custom payloads into vulnerable network endpoints. Cuts job duration significantly and boosts all passive income.',
    rarity: 'rare',
    category: 'contract',
    stats: { contractSpeedBonus: 1.6, incomeMultiplier: 1.15 },
    cost: 950,
    cpu: 2, ram: 3, gpu: 0,
  },
];

const CONTRACTS = [
  {
    id: 'hash_job_01',
    from: 'anon_47',
    subject: 'Quick job — hashes',
    body: `Got a hash dump that needs tearing through. About 200 entries, standard SHA-256. Nothing exotic.\n\nPaying flat rate on delivery. Don't sit on this.`,
    reward: 320,
    duration: 45,
    expiresIn: 180,
    spawnDelay: 15,
    followUp: `Opportunity closed. Don't waste my time next time.`,
  },
  {
    id: 'data_pull_01',
    from: 'mr.null',
    subject: 'Data pull — urgent',
    body: `Client needs a clean scrape off a target list. Anonymized output, standard format. You know the drill.\n\nTime sensitive. Rate is non-negotiable.`,
    reward: 480,
    duration: 60,
    expiresIn: 240,
    spawnDelay: 100,
    followUp: `Fine. Found someone else. Next time respond faster.`,
  },
  {
    id: 'hash_job_02',
    from: 'c1pher',
    subject: 'Bulk hash job',
    body: `Bigger job this time. Full bcrypt dump, around 1,200 hashes. Whoever did the last batch did decent work so I'm back.\n\nExpect it to take some compute. Rate reflects that.`,
    reward: 1100,
    duration: 90,
    expiresIn: 300,
    spawnDelay: 240,
    followUp: `Your loss.`,
  },
  {
    id: 'endpoint_job_01',
    from: 'v01d',
    subject: 'Endpoint access',
    body: `Need a foot in the door on a target endpoint. I'll handle everything downstream. Just need the initial injection handled cleanly.\n\nPays well because the target has some defences. Tool selection is your problem — pick something that fits.`,
    reward: 2200,
    duration: 120,
    expiresIn: 360,
    spawnDelay: 420,
    followUp: `Surprised you passed on this one. Their defences weren't that scary.`,
  },
];

const OPERATIONS = [
  {
    id: 'bandwidth_leasing',
    name: 'Bandwidth Leasing',
    description: 'Sell unused bandwidth to a proxy network.',
    incomePerSec: 0.5,
    requiredScript: 'proxy_tunnel',
  },
  {
    id: 'data_harvesting',
    name: 'Data Harvesting',
    description: 'Scrape and sell anonymized user data to brokers.',
    incomePerSec: 2.0,
    requiredScript: 'scraper_v1',
  },
  {
    id: 'gpu_mining',
    name: 'GPU Mining',
    description: 'Mine anonymous cryptocurrency using available VRAM.',
    incomePerSec: 0.25,
    cpu: 0, ram: 0, gpu: 2,
  },
];

const HARDWARE = {
  cpu: {
    name: 'CPU',
    unit: 'cores',
    section: 'PROCESSORS',
    tiers: [
      { label: 'Dual-Core 2.4GHz',  model: 'CoreX D2-2400',     spec: '2 cores / 2.4 GHz',  capacity: 2,  cost: 0    },
      { label: 'Quad-Core 3.2GHz',  model: 'CoreX Q4-3200',     spec: '4 cores / 3.2 GHz',  capacity: 4,  cost: 150  },
      { label: 'Octa-Core 4.0GHz',  model: 'CoreX X8-4000',     spec: '8 cores / 4.0 GHz',  capacity: 8,  cost: 600  },
      { label: '16-Core 5.0GHz',    model: 'CoreX Ultra X16',   spec: '16 cores / 5.0 GHz', capacity: 16, cost: 2500 },
    ],
  },
  ram: {
    name: 'RAM',
    unit: 'GB',
    section: 'MEMORY',
    tiers: [
      { label: '4 GB DDR4',  model: 'MemTech Baseline 4G',  spec: '4 GB / DDR4-3200',  capacity: 4,  cost: 0    },
      { label: '8 GB DDR4',  model: 'MemTech Standard 8G',  spec: '8 GB / DDR4-3600',  capacity: 8,  cost: 100  },
      { label: '16 GB DDR5', model: 'MemTech Pro 16G',      spec: '16 GB / DDR5-4800', capacity: 16, cost: 450  },
      { label: '32 GB DDR5', model: 'MemTech Apex 32G',     spec: '32 GB / DDR5-6000', capacity: 32, cost: 1800 },
    ],
  },
  gpu: {
    name: 'GPU',
    unit: 'GB VRAM',
    section: 'GRAPHICS',
    tiers: [
      { label: 'Integrated 2GB',  model: 'Onboard iGFX',        spec: '2 GB VRAM / shared',  capacity: 2,  cost: 0    },
      { label: 'VidForce GTX-6',  model: 'VidForce GTX-6',      spec: '6 GB VRAM / GDDR6',   capacity: 6,  cost: 300  },
      { label: 'VidForce RTX-8',  model: 'VidForce RTX-8 Pro',  spec: '8 GB VRAM / GDDR6X',  capacity: 8,  cost: 900  },
      { label: 'VidForce RTX-24', model: 'VidForce RTX-24 XT',  spec: '24 GB VRAM / GDDR7',  capacity: 24, cost: 3500 },
      
    ],
  },
};
