const SCRIPTS = [
  {
    id: 'ssh_brute',
    filename: 'ssh_brute.sh',
    description: 'Dictionary-based SSH attack tool. Reliable against unprotected workstations, limited against hardened targets.',
    rarity: 'uncommon',
    category: 'network',
    stats: {},
    cost: 200,
    cpu: 2, ram: 1, gpu: 0,
  },
  {
    id: 'exploit_kit',
    filename: 'exploit_kit.py',
    description: 'Modular exploit framework. Chains known CVEs for access to servers and corporate infrastructure.',
    rarity: 'rare',
    category: 'network',
    stats: {},
    cost: 1800,
    cpu: 4, ram: 4, gpu: 0,
  },
  {
    id: 'corp_bleeder',
    filename: 'corp_bleeder.py',
    description: 'Silent financial drain. Siphons micro-transactions from compromised corporate servers over time. High exposure risk.',
    rarity: 'legendary',
    category: 'network',
    stats: {},
    cost: 5000,
    cpu: 2, ram: 4, gpu: 0,
  },
  {
    id: 'proxy_tunnel',
    filename: 'proxy_tunnel.sh',
    description: 'Routes traffic through anonymous proxy nodes. Core tool for passive bandwidth operations.',
    rarity: 'common',
    category: 'automation',
    stats: {},
    cost: 50,
    cpu: 1, ram: 1, gpu: 0,
    unlocksOperation: 'bandwidth_leasing',
  },
  {
    id: 'scraper_v1',
    filename: 'scraper_v1.py',
    description: 'Harvests and packages user data from public endpoints. Standard automation tool.',
    rarity: 'common',
    category: 'automation',
    stats: {},
    cost: 200,
    cpu: 2, ram: 4, gpu: 0,
    unlocksOperation: 'data_harvesting',
  },
  {
    id: 'hash_cracker_basic',
    filename: 'hash_cracker_basic.py',
    description: 'Entry-level hash cracker. Single-threaded, slow, but gets the job done. Cracks one wallet hash at a time.',
    rarity: 'common',
    category: 'contract',
    stats: { parallelCracks: 1 },
    cost: 0,
    cpu: 1, ram: 1, gpu: 0,
  },
  {
    id: 'hash_cracker',
    filename: 'hash_cracker.py',
    description: 'Multi-threaded hash cracker with wordlist support. Runs 2 wallet hashes in parallel and speeds up contract work.',
    rarity: 'uncommon',
    category: 'contract',
    stats: { contractSpeedBonus: 1.3, parallelCracks: 2 },
    cost: 350,
    cpu: 3, ram: 2, gpu: 0,
  },
  {
    id: 'hash_cracker_v2',
    filename: 'hash_cracker_v2.py',
    description: 'Enhanced cracking suite with GPU acceleration. Runs 3 wallet hashes in parallel with improved throughput.',
    rarity: 'rare',
    category: 'contract',
    stats: { contractSpeedBonus: 1.6, parallelCracks: 3 },
    cost: 2200,
    cpu: 5, ram: 4, gpu: 0,
  },
  {
    id: 'hash_cracker_v3',
    filename: 'hash_cracker_v3.py',
    description: 'Military-grade cracking engine. Handles 4 parallel hash jobs with near-optimal throughput and 2× speed.',
    rarity: 'legendary',
    category: 'contract',
    stats: { contractSpeedBonus: 2.0, parallelCracks: 4 },
    cost: 7500,
    cpu: 6, ram: 8, gpu: 2,
  },
  {
    id: 'payload_inj',
    filename: 'payload_inj.sh',
    description: 'Injects custom payloads into vulnerable network endpoints. Cuts job duration significantly and boosts all passive income.',
    rarity: 'rare',
    category: 'contract',
    stats: { contractSpeedBonus: 1.6, incomeMultiplier: 1.15 },
    cost: 950,
    cpu: 2, ram: 3, gpu: 0,
  },
  {
    id: 'stealth_basic',
    filename: 'stealth_basic.sh',
    description: 'Basic traffic obfuscation. Masks footprint during sensitive operations. Required for tier 1 stealth contracts.',
    rarity: 'uncommon',
    category: 'stealth',
    stats: {},
    cost: 900,
    cpu: 1, ram: 1, gpu: 0,
  },
  {
    id: 'ghost_protocol',
    filename: 'ghost_protocol.py',
    description: 'Advanced anonymization suite. Deep packet masking and honeypot evasion. Required for tier 2 stealth contracts.',
    rarity: 'rare',
    category: 'stealth',
    stats: {},
    cost: 3500,
    cpu: 3, ram: 3, gpu: 0,
  },
  {
    id: 'phantom_kernel',
    filename: 'phantom_kernel.ko',
    description: 'Kernel-level invisibility module. Near-undetectable. Required for tier 3 stealth contracts.',
    rarity: 'legendary',
    category: 'stealth',
    stats: {},
    cost: 14000,
    cpu: 4, ram: 6, gpu: 0,
  },
];

// Contracts are generated dynamically in game.js — see _generateContract()

const OPERATIONS = [
  {
    id: 'bandwidth_leasing',
    name: 'Bandwidth Leasing',
    description: 'Sell unused bandwidth to a proxy network.',
    incomePerSec: 0.5,
    requiredScript: 'proxy_tunnel',
  },
  {
    id: 'data_harvesting',
    name: 'Data Harvesting',
    description: 'Scrape and sell anonymized user data to brokers.',
    incomePerSec: 2.0,
    requiredScript: 'scraper_v1',
  },
  {
    id: 'gpu_mining',
    name: 'GPU Mining',
    description: 'Mine anonymous cryptocurrency using available VRAM.',
    incomePerSec: 0.25,
    cpu: 0, ram: 0, gpu: 2,
  },
];

const HARDWARE = {
  cpu: {
    name: 'CPU',
    unit: 'cores',
    section: 'PROCESSORS',
    tiers: [
      { label: 'Dual-Core 2.4GHz',  model: 'CoreX D2-2400',     spec: '2 cores / 2.4 GHz',  capacity: 2,  cost: 0    },
      { label: 'Quad-Core 3.2GHz',  model: 'CoreX Q4-3200',     spec: '4 cores / 3.2 GHz',  capacity: 4,  cost: 150  },
      { label: 'Octa-Core 4.0GHz',  model: 'CoreX X8-4000',     spec: '8 cores / 4.0 GHz',  capacity: 8,  cost: 600  },
      { label: '16-Core 5.0GHz',    model: 'CoreX Ultra X16',   spec: '16 cores / 5.0 GHz', capacity: 16, cost: 2500 },
    ],
  },
  ram: {
    name: 'RAM',
    unit: 'GB',
    section: 'MEMORY',
    tiers: [
      { label: '4 GB DDR4',  model: 'MemTech Baseline 4G',  spec: '4 GB / DDR4-3200',  capacity: 4,  cost: 0    },
      { label: '8 GB DDR4',  model: 'MemTech Standard 8G',  spec: '8 GB / DDR4-3600',  capacity: 8,  cost: 100  },
      { label: '16 GB DDR5', model: 'MemTech Pro 16G',      spec: '16 GB / DDR5-4800', capacity: 16, cost: 450  },
      { label: '32 GB DDR5', model: 'MemTech Apex 32G',     spec: '32 GB / DDR5-6000', capacity: 32, cost: 1800 },
    ],
  },
  gpu: {
    name: 'GPU',
    unit: 'GB VRAM',
    section: 'GRAPHICS',
    tiers: [
      { label: 'Integrated 2GB',  model: 'Onboard iGFX',        spec: '2 GB VRAM / shared',  capacity: 2,  cost: 0    },
      { label: 'VidForce GTX-6',  model: 'VidForce GTX-6',      spec: '6 GB VRAM / GDDR6',   capacity: 6,  cost: 300  },
      { label: 'VidForce RTX-8',  model: 'VidForce RTX-8 Pro',  spec: '8 GB VRAM / GDDR6X',  capacity: 8,  cost: 900  },
      { label: 'VidForce RTX-24', model: 'VidForce RTX-24 XT',  spec: '24 GB VRAM / GDDR7',  capacity: 24, cost: 3500 },
      
    ],
  },
};
